### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by ThisAngryman** [Echo-Ji/ST-SSL#11]
感谢您出色的工作，我想知道原始的数据集是如何变成.npz文件的？能否提供对应的转换代码。再次感谢！

**Comment by Echo-Ji** [comment]
感谢您的关注，请查看我们的[新分支](https://github.com/Echo-Ji/ST-SSL/tree/feature/data-preprocessing)，该分支的scripts文件夹提供了您需要的代码。
