### ISSUE TITLE
about adj_mx.npz

### ISSUE THREAD

**Issue by black-angela** [Echo-Ji/ST-SSL#12]
Excuse me, I would like to ask how to generate the adj_mx.npz file?

**Comment by Echo-Ji** [comment]
Thanks for your attention and sorry for the late reply. Please refer to this comment: https://github.com/Echo-Ji/ST-SSL/issues/7#issuecomment-2482329361.

**Comment by Echo-Ji** [comment]
You can also refer to the `scripts` directory of our [new branch](https://github.com/Echo-Ji/ST-SSL/tree/feature/data-preprocessing).
