### ISSUE TITLE
about config of BJTaxi

### ISSUE THREAD

**Issue by 805ya** [Echo-Ji/ST-SSL#13]
Hello, I want to make sure that the value of d_input here is correct

## model 
d_input: 1                  # means inflow and outflow
d_output: 2                 # means inflow and outflow
d_model: 64

**Comment by Echo-Ji** [comment]
Thanks for double-checking. d_input should be 2 instead of 1. We have corrected this in the latest code😄

**Comment by Echo-Ji** [comment]
Bug fixed 🐛
