### ISSUE TITLE
关于loss的问题

### ISSUE THREAD

**Issue by Dench991228** [Echo-Ji/ST-SSL#14]
请问原文中的equation 8的损失函数实装了吗？我看代码里面的损失函数（model/layers/SpatialHeteroModel/forward）和equation 5非常相似，但是肯定不是equation 8？以及我没有找到附录，可以提供吗？

**Comment by Echo-Ji** [comment]
感谢您的关注😸 
Eq. 8的优化过程体现在这里：
https://github.com/Echo-Ji/ST-SSL/blob/b3f3dfc48d12524c207cc89f4e242cb8aac081c0/model/layers.py#L54
带附录的论文版本可以在这里找到：
https://echo-ji.github.io/academicpages/files/STSSL_AAAI23.pdf
