### ISSUE TITLE
  File "D:\AICode\ST-SSL\model\aug.py", line 53, in aug_topology     drop_prob = torch.softmax(sim_mx[edge_mask], dim=0) RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by XiangMeng666** [Echo-Ji/ST-SSL#3]
I encountered the following problem when running the program, I debugging found that the sim_mx is in cpu, edge_mask is in gpu, and then I change the edge_mask to CPU, and the program can run successfully, i want to ensure whether changing this place is right?

my change is :      edge_mask = (input_graph > 0).tril(diagonal=-1).cpu()

**Comment by Echo-Ji** [comment]
Yes, moving edge_mask to CPU is correct.
