### ISSUE TITLE
How to change dataset?

### ISSUE THREAD

**Issue by GuFan26** [Echo-Ji/ST-SSL#5]
Hi,I want to ask that how to run the projects with another dataset. Now,I can successfully run the projects with the dataset NYCBike 1,but i don't know how to change it into BJTaxi.

**Comment by Echo-Ji** [comment]
You can make a directory named `BJTaxi` and put the relevant data here.

Next, you can directly run it with the following code:

```
> ./runme.sh 0 BJTaxi
```

Good luck!
