### ISSUE TITLE
数据集的一点问题

### ISSUE THREAD

**Issue by waynedu925** [Echo-Ji/ST-SSL#6]
请问作者raw dataset有吗，我想对数据集重新进行处理来适配我的模型，但我在网上并没有找到数据集的原始版本，在您提供的数据集中划分的是19个时间片，我想拿到原始数据来重新划分一个sample含有更多的时间片，因为我看到x_offset中的数据是[[-73][-72][-71][-70][-69][-49][-48][-47][-46][-45][-25][-24][-23][-22][-21][ -3][ -2][ -1][  0]]，我感觉直接用第一维度乘以第二维度来获得连续的总的时间片是不太靠谱的，所以想请教下您应该怎么做呢？谢谢

**Comment by Echo-Ji** [comment]
请从这里下载原始数据集：#9
